**Ejercicio 3.2.6
Dados dos arrays, a y b, con valores, 1,2,3 y 4,5,6 respectivamente. Calcula la división de a entre b y muestra por pantalla 
un nuevo array cuyos elementos serán, respectivamente, los valores de a, los valores de b y el resultado de la división entre
a y b.**

In [1]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])

divide = A/B

nuevo = np.array([A,B,divide])
print(nuevo)


[[1.   2.   3.  ]
 [4.   5.   6.  ]
 [0.25 0.4  0.5 ]]


In [7]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A *= 6
B *= 6
total = np.array([A,B])
print(A)
print(B)
print(total)
print(f"El tipo de elementos son {total.dtype} y tienen las siguientes filas y columnas {total.shape}")



[ 6 12 18]
[24 30 36]
[[ 6 12 18]
 [24 30 36]]
El tipo de elementos son int32 y tienen las siguientes filas y columnas (2, 3)


In [14]:
import pandas as pd
serie = pd.Series([4,8,6,2,7,8,2,1,9])
#serie_ordenada = serie.sort_values()
print(serie)
#print(serie_ordenada)



0    4
1    8
2    6
3    2
4    7
5    8
6    2
7    1
8    9
dtype: int64


In [34]:
import pandas as pd
import string
a = pd.Series([4,8,6,2,7,8,2,1,9])
letras = list(string.ascii_uppercase)[:len(a)]
a.index = letras
print(a)

A    4
B    8
C    6
D    2
E    7
F    8
G    2
H    1
I    9
dtype: int64


In [20]:
import pandas as pd
serie = pd.Series([4,8,6,2,7,8,2,1,9],index = list("abcdefghi"))

#print(serie)
print(serie["e"])


7


In [21]:
#ejemplo diccionario

import pandas
diccionario = {1:"rojo", 2: "verde", 3: "azul"}
serie = pandas.Series(diccionario)

print(serie)
print(serie[1])

1     rojo
2    verde
3     azul
dtype: object
rojo


In [26]:
import pandas as pd
A = pd.Series([1,5,3,8])
B = pd.Series([4,8,3,9])

resto = A%B


print(resto)

0    1
1    5
2    0
3    8
dtype: int64


In [28]:
import pandas as pd
a = pd.Series([1,4,6,8])
multiplicar = a*4
print(multiplicar)

0     4
1    16
2    24
3    32
dtype: int64


In [39]:
serie = pd.Series([4,8,6,2,7,8,2,1,9])
s = pd.Series([0,0,0,0,0,0,0,0])
for i in range(len(serie)-1):
    s[i] = serie[i]+serie[i+1]
print(s)

0    12
1    14
2     8
3     9
4    15
5    10
6     3
7    10
dtype: int64
